### ISSUE TITLE
CUDA Out of Memory Error when Running with --augment Flag

### ISSUE THREAD

**Issue by yogipuji15** [kutaytire/Retrieval-Augmented-Time-Series-Forecasting#1]
I am facing an issue when running my code with augmentation in my project. When I run the command `python run_chronos.py /home/tifzaki/chronos-research/Retrieval-Augmented-Time-Series-Forecasting/configs/benchmark-1/etth.yaml result.csv --no-augment` , it completes successfully without any errors. However, when I try to run it with augmentation using the command `python run_chronos.py /home/tifzaki/chronos-research/Retrieval-Augmented-Time-Series-Forecasting/configs/benchmark-1/etth.yaml result.csv --augment` , I receive a "CUDA Out of Memory" error like this:
```
/home/tifzaki/miniconda3/envs/chronos-raf/lib/python3.12/site-packages/gluonts/json.py:102: UserWarning: Using `json`-module for json-handling. Consider installing one of `orjson`, `ujson` to speed up serialization and deserialization.
  warnings.warn(
2024-11-18 16:00:50,631 - Chronos Evaluation - INFO - Loading ETTh
2024-11-18 16:00:54,155 - Chronos Evaluation - INFO - Generating forecasts for ETTh (4 time series)
0it [00:00, ?it/s]/home/tifzaki/chronos-research/Retrieval-Augmented-Time-Series-Forecasting/time_series_utils.py:50: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast():
0it [00:04, ?it/s]
0it [00:05, ?it/s]
Traceback (most recent call last):
  File "/home/tifzaki/chronos-research/Retrieval-Augmented-Time-Series-Forecasting/run_chronos.py", line 380, in <module>
    app()
  File "/home/tifzaki/miniconda3/envs/chronos-raf/lib/python3.12/site-packages/typer/main.py", line 338, in __call__
    raise e
  File "/home/tifzaki/miniconda3/envs/chronos-raf/lib/python3.12/site-packages/typer/main.py", line 321, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tifzaki/miniconda3/envs/chronos-raf/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tifzaki/miniconda3/envs/chronos-raf/lib/python3.12/site-packages/typer/core.py", line 665, in main
    return _main(
           ^^^^^^
  File "/home/tifzaki/miniconda3/envs/chronos-raf/lib/python3.12/site-packages/typer/core.py", line 197, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/tifzaki/miniconda3/envs/chronos-raf/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tifzaki/miniconda3/envs/chronos-raf/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tifzaki/miniconda3/envs/chronos-raf/lib/python3.12/site-packages/typer/main.py", line 703, in wrapper
    return callback(**use_params)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tifzaki/chronos-research/Retrieval-Augmented-Time-Series-Forecasting/run_chronos.py", line 332, in main
    sample_forecasts = generate_sample_forecasts(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tifzaki/chronos-research/Retrieval-Augmented-Time-Series-Forecasting/run_chronos.py", line 264, in generate_sample_forecasts
    context,mean_std_values = augment_time_series(train_df, pipeline, context, prediction_length, top_n)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tifzaki/chronos-research/Retrieval-Augmented-Time-Series-Forecasting/time_series_utils.py", line 91, in augment_time_series
    best_matches = find_best_matches_full_series_batch(train_df, context_tensor_matrix, test_length, prediction_length, pipeline, top_n)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tifzaki/chronos-research/Retrieval-Augmented-Time-Series-Forecasting/time_series_utils.py", line 51, in find_best_matches_full_series_batch
    other_embeddings, _ = pipeline.embed(batch_tensor)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tifzaki/miniconda3/envs/chronos-raf/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tifzaki/chronos-research/Retrieval-Augmented-Time-Series-Forecasting/chronos_local.py", line 447, in embed
    embeddings = self.model.encode(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/tifzaki/chronos-research/Retrieval-Augmented-Time-Series-Forecasting/chronos_local.py", line 307, in encode
    return self.model.encoder(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tifzaki/miniconda3/envs/chronos-raf/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tifzaki/miniconda3/envs/chronos-raf/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tifzaki/miniconda3/envs/chronos-raf/lib/python3.12/site-packages/transformers/models/t5/modeling_t5.py", line 1033, in forward
    extended_attention_mask = self.get_extended_attention_mask(attention_mask, input_shape)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tifzaki/miniconda3/envs/chronos-raf/lib/python3.12/site-packages/transformers/modeling_utils.py", line 1169, in get_extended_attention_mask
    extended_attention_mask = (1.0 - extended_attention_mask) * torch.finfo(dtype).min
                               ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
  File "/home/tifzaki/miniconda3/envs/chronos-raf/lib/python3.12/site-packages/torch/_tensor.py", line 41, in wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/tifzaki/miniconda3/envs/chronos-raf/lib/python3.12/site-packages/torch/_tensor.py", line 962, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 24.00 MiB. GPU 1 has a total capacity of 11.76 GiB of which 3.25 MiB is free. Process 3204 has 102.00 MiB memory in use. Including non-PyTorch memory, this process has 11.65 GiB memory in use. Of the allocated memory 11.52 GiB is allocated by PyTorch, and 4.29 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```
My GPU Specifications:
- GPU: NVIDIA GeForce RTX 3060
- Driver Version: 535.216.01
- CUDA Version: 12.2
- Total Memory: 12 GB

**Comment by kutaytire** [comment]
Hi,
Some of the datasets, such as Weather, Traffic, and ETTh, are quite large. When you are trying to retrieve the best-matching time series from the database, it seems that your GPU memory is insufficient. You may try the following:

- Reduce the batch size for the test examples.

- During the retrieval process, the distances between each time series in the database and your original time series are calculated on the GPU. So, you may try reducing the batch size within _find_best_matches_full_series_batch_ function.

- Increase the step size inside the _find_best_matches_full_series_batch_ function. Naturally, this will skip some indices when finding the best match from the database, and the retrieved time series may be suboptimal, so be aware of this.

For context, we used NVIDIA A100s with 40GB. Even so, I had to increase the step size for the Weather and Traffic datasets to save space.
